pipeline {
    agent any 
	
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        // 这里的hello2 是我加的，就是说明，这是stages下的第二个任务 ,就是在pipeline中加单行注释 用 // 就行
        stage('PWD') {
            steps {
                sh 'pwd'
            }
        }
	stage('Build'){
	    steps {
	    dir('/var/lib/jenkins/workspace/wxjj_Jenkinsfile-test/fibonacci') {
                    // 在指定目录中执行脚本
                    sh './build.sh'
                }
	    }
	}	
    }
}
