pipeline {
    agent any 
	
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        // 这里的hello2 是我加的，就是说明，这是stages下的第二个任务 ,就是在pipeline中加单行注释 用 // 就行
        stage('PWD') {
            steps {
                sh 'pwd'
            }
        }
	stage('Build'){
          steps {
	    sh 'cd fibonacci'
	    sh 'pwd'
            sh './build.sh'
          }
	}	
    }
}
