pipeline {
    agent any 
	
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
	stage('Build'){
	    steps {
	    	script {
                    // 获取当前目录位置并保存到变量中
                    def currentDir = pwd()
                    
                    // 打印当前目录位置
                    echo "Current Directory: ${currentDir}"
                    
		    dir('${./fibonacci') {
                    // 在指定目录中执行脚本
                    sh './build.sh'
               	    }
	   	 }
	     }	
         }
    }
}
